spring.application.name=nms

spring.datasource.url=${DB_URL:jdbc:h2:mem:notification;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER_CLASS_NAME:org.h2.Driver}

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
